# numpy Assignment

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
import numpy as np
import pandas as pd

In [3]:
def generate_atv_matrix(in_vector, n, increasing=False):
    return np.vander(in_vector, n, increasing)

in_vector = [1, 2, 3, 4, 5]
n = 10
l1 = generate_atv_matrix(in_vector, n, True)
print(*l1, sep='\n')

[1 1 1 1 1 1 1 1 1 1]
[  1   2   4   8  16  32  64 128 256 512]
[    1     3     9    27    81   243   729  2187  6561 19683]
[     1      4     16     64    256   1024   4096  16384  65536 262144]
[      1       5      25     125     625    3125   15625   78125  390625
 1953125]


In [4]:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
# the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
def calc_moving_avg(in_vector, winlen):
    vec_len = len(in_vector)
    avg_val_num = vec_len - winlen + 1
    out_vec = []
    start_idx = 0
    for i in range(avg_val_num):
        cur_vec = in_vector[start_idx:winlen+start_idx]
        avg_val = np.cumsum(cur_vec)[winlen-1] / winlen
        out_vec.append(avg_val)
        start_idx += 1
    return out_vec

a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
b = calc_moving_avg(a,3)
print(*b, sep='\n')

5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333
